init:
- source $HOME/.rvm/bin/rvm
- echo $DIR
- echo $MONITOR_PID
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE

test_script:
- ps
- sh: |
    shopt -q login_shell && echo Login shell || echo Not login shell
- sh: |
    [[ $- == *i* ]] && echo Interactive || echo Not interactive
- sh: rvm use 2.3
- sh: command -v ruby
- sh: ruby --version
- sh: |
    #rm $DIR/exit
    #kill $MONITOR_PID
    exit 2

build: off
