init:
- echo $DIR
- echo $MONITOR_PID
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE

test_script:
- ps
- sh: rvm use 2.3
- sh: |
    #rm $DIR/exit
    #kill $MONITOR_PID
    exit 2

build: off
